version: '3'
services:
  postgres:
    build:
      context: ./db
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d