version: '3'
services:
  postgres:
    image: postgres:14.9
    container_name: ir-server-postgres
    env_file:
      - ./db/.env
    hostname: postgres-host
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
    pull_policy: "always"
    depends_on:
     - postgres
    container_name: ir-server-api
    env_file:
      - ./ir_server_api/.env
    ports:
      - 8080:8000
    volumes:
      - ./ir_server_api/:/usr/src/app/ir_server_api/
      - ./images/:/var/www/ir_server_api/images/
    working_dir: /usr/src/app/ir_server_api
    command: ["gunicorn", "--config", "gunicorn_settings.py"]