# Generated by Django 4.2 on 2023-08-19 00:41

from django.db import migrations, models
import uuid
import wallpaper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ImageField(blank=True, null=True, upload_to=wallpaper.models.upload_to)),
            ],
        ),
    ]
