# Generated by Django 4.2 on 2023-08-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='content',
            new_name='file',
        ),
    ]
