# Generated by Django 4.2 on 2023-09-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ir_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ir_server_user',
        ),
    ]
