# Generated by Django 4.2 on 2023-11-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ir_server', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
